server:
  port: 9010
spring:
  application:
    name: ms10-discovery-eureka-auth-register
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:9009/eureka/  #注册到带密码的注册中心
  
  instance:
    prefer-ip-address: true