server:
  port: 9009
spring:
  application:
    name: ms09-discovery-eureka-auth-register
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:9008/eureka/  #注册到带密码的注册中心
  
  instance:
    prefer-ip-address: true