server:
  port: 9009
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9009/eureka/
    register-with-eureka: false
    fetch-registry: false
security:
  basic:
    enabled: true  #开启基于http basic的认证
  user:  #如果不设置user,用户名默认user,密码会在启动程序时打出
    name: root
    password: root
  