server:
  port: 9001
logging:
  level:
    root: INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    version: @project.version@
    java:
      source: @java.version@